package com.eduardo.idealista.scrapper

import com.eduardo.idealista.model.SearchTerms
import spock.lang.Specification
import spock.lang.Unroll

/**
 * Created by hedu on 6/04/17.
 */
class IdealistaUrlGeneratorSpec extends Specification {

    @Unroll
    void '''#url is generated for parameters city : #city, neighborhood : #neighborhood,
        maxPrice : #maxPrice, minRooms : #minRooms, includeGroundFloor : #includeGroundFloor,
        picturesRequired : #picturesRequired and publishedPeriod : #publishedPeriod'''() {

        expect: 'url generated on idealista search matches the one generated by generateUrl method'

        IdealistaUrlGenerator.generateSearchUrl(city, neighborhood, maxPrice, minRooms,
                includeGroundFloor, picturesRequired, publishedPeriod) == url

        where:
        city     | neighborhood | maxPrice | minRooms | includeGroundFloor | picturesRequired | publishedPeriod                       | url
        "madrid" | "chamberi"   | -1       | -1       | true               | false            | SearchTerms.PublishedPeriod.all       | "https://www.idealista.com/alquiler-viviendas/madrid/chamberi"
        "madrid" | "chamberi"   | 650      | -1       | true               | false            | SearchTerms.PublishedPeriod.all | "https://www.idealista.com/alquiler-viviendas/madrid/chamberi/con-precio-hasta_650"
        "madrid" | "chamberi"   | -1       | 1        | true               | false            | SearchTerms.PublishedPeriod.all | "https://www.idealista.com/alquiler-viviendas/madrid/chamberi/de-un-dormitorio,de-dos-dormitorios,de-tres-dormitorios,de-cuatro-cinco-habitaciones-o-mas"
        "madrid" | "chamberi"   | -1       | -1       | false              | false            | SearchTerms.PublishedPeriod.all       | "https://www.idealista.com/alquiler-viviendas/madrid/chamberi/ultimas-plantas,plantas-intermedias"
        "madrid" | "chamberi"   | -1       | -1       | true               | true             | SearchTerms.PublishedPeriod.all       | "https://www.idealista.com/alquiler-viviendas/madrid/chamberi/fotos-o-video"
        "madrid" | "chamberi"   | -1       | -1       | true               | false            | SearchTerms.PublishedPeriod.lastDay   | "https://www.idealista.com/alquiler-viviendas/madrid/chamberi/publicado_ultimas-24-horas"
        "madrid" | "chamberi"   | -1       | -1       | true               | false            | SearchTerms.PublishedPeriod.lastWeek  | "https://www.idealista.com/alquiler-viviendas/madrid/chamberi/publicado_ultima-semana"
        "madrid" | "chamberi"   | -1       | -1       | true               | false            | SearchTerms.PublishedPeriod.lastMonth | "https://www.idealista.com/alquiler-viviendas/madrid/chamberi/publicado_ultimo-mes"
        "madrid" | "chamberi"   | 650      | 1        | false              | true             | SearchTerms.PublishedPeriod.lastDay   | "https://www.idealista.com/alquiler-viviendas/madrid/chamberi/con-precio-hasta_650,de-un-dormitorio,de-dos-dormitorios,de-tres-dormitorios,de-cuatro-cinco-habitaciones-o-mas,ultimas-plantas,plantas-intermedias,fotos-o-video,publicado_ultimas-24-horas"
    }

    void 'check flat url is created as expected'() {

        expect: 'flat href is appended to the base url'

        IdealistaUrlGenerator.getFlatUrl("/inmueble/36576377/") == "https://www.idealista.com/inmueble/36576377/"
    }
}
